[package]

name = "tcp-ayce"
version = "0.0.0"
authors = ["Lorenzo Martini <lmartini@student.ethz.ch>"]
readme = "README.md"

description = "A Rust program to shove data through TCP sockets:"

[dependencies]
bytes={version="*", features=["i128"]}
